-- MySQL Script generated by MySQL Workbench
-- Ter 19 Set 2017 14:42:44 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema monitoria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema monitoria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `monitoria` DEFAULT CHARACTER SET latin1 ;
USE `monitoria` ;

-- -----------------------------------------------------
-- Table `monitoria`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoria`.`admins` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `admins_email_unique` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `monitoria`.`bolsas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoria`.`bolsas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quantidade` INT(2) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `monitoria`.`dados_bancarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoria`.`dados_bancarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(11) NOT NULL,
  `agencia` VARCHAR(11) NOT NULL,
  `conta_corrente` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 62
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `monitoria`.`descricao_periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoria`.`descricao_periodo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `monitoria`.`tipo_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoria`.`tipo_disciplina` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `monitoria`.`disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoria`.`disciplinas` (
  `cod_disciplina` INT(11) UNSIGNED NOT NULL,
  `nome` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `fk_tipo_disciplina_id` INT(11) NOT NULL DEFAULT '2',
  `c_prat` INT(11) NOT NULL DEFAULT '0',
  `c_teor` INT(11) NOT NULL DEFAULT '0',
  `c_est` INT(11) NOT NULL DEFAULT '0',
  `c_ext` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`cod_disciplina`),
  INDEX `disciplinas_cod_disciplina_index` (`cod_disciplina` ASC),
  INDEX `fk_disciplinas_tipo_disciplina1_idx` (`fk_tipo_disciplina_id` ASC),
  CONSTRAINT `fk_disciplinas_tipo_disciplina1`
    FOREIGN KEY (`fk_tipo_disciplina_id`)
    REFERENCES `monitoria`.`tipo_disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `monitoria`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoria`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `monitoria`.`status_monitoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoria`.`status_monitoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `monitoria`.`status_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoria`.`status_turma` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `monitoria`.`vagas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoria`.`vagas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `t_total` INT(11) NOT NULL DEFAULT '0',
  `t_ocupadas` INT(11) NOT NULL DEFAULT '0',
  `t_restantes` INT(11) NOT NULL DEFAULT '0',
  `c_total` INT(11) NOT NULL DEFAULT '0',
  `c_ocupadas` INT(11) NOT NULL DEFAULT '0',
  `c_restantes` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 427
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `monitoria`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoria`.`turmas` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `turma` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `professor` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `fk_cod_disciplina` INT(11) UNSIGNED NOT NULL,
  `fk_status_turma_id` INT(11) NOT NULL DEFAULT '3',
  `qnt_bolsas` INT(11) NOT NULL DEFAULT '0',
  `fk_vagas_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_turmas_disciplinas1_idx` (`fk_cod_disciplina` ASC),
  INDEX `fk_turmas_status_turma1_idx` (`fk_status_turma_id` ASC),
  INDEX `fk_turmas_vagas1_idx` (`fk_vagas_id` ASC),
  CONSTRAINT `fk_turmas_disciplinas1`
    FOREIGN KEY (`fk_cod_disciplina`)
    REFERENCES `monitoria`.`disciplinas` (`cod_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turmas_status_turma1`
    FOREIGN KEY (`fk_status_turma_id`)
    REFERENCES `monitoria`.`status_turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turmas_vagas1`
    FOREIGN KEY (`fk_vagas_id`)
    REFERENCES `monitoria`.`vagas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 427
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `monitoria`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoria`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `cpf` VARCHAR(11) CHARACTER SET 'utf8' NOT NULL,
  `rg` VARCHAR(11) CHARACTER SET 'utf8' NOT NULL,
  `matricula` VARCHAR(11) CHARACTER SET 'utf8' NOT NULL,
  `fk_banco` INT(11) NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `matricula`),
  UNIQUE INDEX `users_email_unique` (`email` ASC),
  UNIQUE INDEX `users_cpf_unique` (`cpf` ASC),
  UNIQUE INDEX `users_rg_unique` (`rg` ASC),
  UNIQUE INDEX `users_matricula_unique` (`matricula` ASC),
  INDEX `fk_banco` (`fk_banco` ASC),
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`fk_banco`)
    REFERENCES `monitoria`.`dados_bancarios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 124
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `monitoria`.`monitoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoria`.`monitoria` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `remuneracao` VARCHAR(45) NOT NULL,
  `fk_matricula` VARCHAR(11) CHARACTER SET 'utf8' NOT NULL,
  `fk_cod_disciplina` INT(11) UNSIGNED NOT NULL,
  `fk_turmas_id` INT(10) NOT NULL,
  `descricao_status` TEXT NULL DEFAULT NULL,
  `prioridade` INT(11) NULL DEFAULT NULL,
  `fk_status_monitoria_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_monitoria_users_idx` (`fk_matricula` ASC),
  INDEX `fk_monitoria_disciplinas1_idx` (`fk_cod_disciplina` ASC),
  INDEX `fk_monitoria_turmas1_idx` (`fk_turmas_id` ASC),
  INDEX `fk_matricula_UNIQUE` (`fk_matricula` ASC),
  INDEX `fk_monitoria_status_monitoria1_idx` (`fk_status_monitoria_id` ASC),
  CONSTRAINT `fk_monitoria_disciplinas1`
    FOREIGN KEY (`fk_cod_disciplina`)
    REFERENCES `monitoria`.`disciplinas` (`cod_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_monitoria_status_monitoria1`
    FOREIGN KEY (`fk_status_monitoria_id`)
    REFERENCES `monitoria`.`status_monitoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_monitoria_turmas1`
    FOREIGN KEY (`fk_turmas_id`)
    REFERENCES `monitoria`.`turmas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_monitoria_users`
    FOREIGN KEY (`fk_matricula`)
    REFERENCES `monitoria`.`users` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `monitoria`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoria`.`password_resets` (
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `token` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC),
  INDEX `password_resets_token_index` (`token` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `monitoria`.`periodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoria`.`periodos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `inicio` TIMESTAMP NULL DEFAULT NULL,
  `fim` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `fk_id_descricao` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_periodos_descricao_periodo1_idx` (`fk_id_descricao` ASC),
  CONSTRAINT `fk_periodos_descricao_periodo1`
    FOREIGN KEY (`fk_id_descricao`)
    REFERENCES `monitoria`.`descricao_periodo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `monitoria`.`professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoria`.`professors` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `username` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `role` INT(11) NOT NULL,
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `professors_username_unique` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
